import { GoogleGenAI } from "@google/genai";

// Helper to convert blob to base64
const blobToBase64 = (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64 = reader.result as string;
      // Remove data url prefix (e.g., "data:image/png;base64,")
      resolve(base64.split(',')[1]); 
    };
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export const aiEditImage = async (
  currentImageBlob: Blob,
  prompt: string
): Promise<Blob> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) throw new Error("API Key is required");

  const ai = new GoogleGenAI({ apiKey });
  const base64Data = await blobToBase64(currentImageBlob);

  // Using gemini-2.5-flash-image for editing capabilities
  const model = "gemini-2.5-flash-image";
  
  const maxRetries = 3;
  let attempt = 0;
  let lastError: any;

  while (attempt < maxRetries) {
    try {
      const response = await ai.models.generateContent({
        model: model,
        contents: {
          parts: [
            {
              text: prompt,
            },
            {
              inlineData: {
                mimeType: currentImageBlob.type || 'image/png',
                data: base64Data,
              },
            },
          ],
        },
      });

      // Extract image from response
      // Check parts for inline data
      const candidates = response.candidates;
      if (candidates && candidates.length > 0) {
        const parts = candidates[0].content?.parts;
        if (parts) {
          for (const part of parts) {
              if (part.inlineData) {
                  const byteString = atob(part.inlineData.data);
                  const arrayBuffer = new ArrayBuffer(byteString.length);
                  const int8Array = new Uint8Array(arrayBuffer);
                  for (let i = 0; i < byteString.length; i++) {
                  int8Array[i] = byteString.charCodeAt(i);
                  }
                  return new Blob([int8Array], { type: 'image/png' });
              }
          }
        }
      }
      
      throw new Error("No image generated by AI");

    } catch (error: any) {
      lastError = error;
      console.warn(`Gemini API Attempt ${attempt + 1} failed:`, error);
      
      // Check for Rate Limit (429) or Quota/Resource Exhausted errors
      const isRateLimit = error.status === 429 || 
                          error.code === 429 || 
                          (error.message && (
                            error.message.includes('429') || 
                            error.message.includes('quota') || 
                            error.message.includes('RESOURCE_EXHAUSTED')
                          ));
      
      if (isRateLimit && attempt < maxRetries - 1) {
        const delay = 2000 * Math.pow(2, attempt); // 2s, 4s, 8s...
        console.log(`Waiting ${delay}ms before retry...`);
        await wait(delay);
        attempt++;
        continue;
      }
      
      // If not a rate limit error or max retries reached, break loop
      break;
    }
  }

  console.error("Gemini API Fatal Error:", lastError);
  throw lastError;
};